# Generated by Django 2.1.1 on 2018-09-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ip_client',
            field=models.CharField(default='123.123.123', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='ip_server',
            field=models.CharField(default='12.12', max_length=400),
            preserve_default=False,
        ),
    ]
